/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import javax.swing.JOptionPane;

/**
 *
 * @author nicolasfischer
 */
public class Ajuda extends javax.swing.JFrame {

    /**
     * Creates new form Ajuda
     */
    public Ajuda() {
       
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAjuda = new javax.swing.JLabel();
        lblEscopoAjuda = new javax.swing.JLabel();
        btnSiteAjuda = new javax.swing.JButton();
        lblUrlAjuda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAjuda.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblAjuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAjuda.setText("Poker Game - Ajuda");

        lblEscopoAjuda.setText("<html><p>&nbsp; &nbsp; &nbsp;Do ingl&ecirc;s <strong>poker</strong>, consiste em um jogo de cartas jogado por duas ou mais pessoas muito comum em&nbsp;casinos. &Eacute; considerado o jogo de cartas mais popular do mundo.</p>\n<p>&nbsp; &nbsp; &nbsp;A partida <span style=\"text-decoration: underline;\">come&ccedil;a</span> da seguinte maneira: o distribuir de cartas p&otilde;e tr&ecirc;s cartas no meio da mesa e duas para cada jogador. Todos tem a chance de apostar. Ap&oacute;s isso, &eacute; virada a quarta carta adicionada ao lado das tr&ecirc;s j&aacute; expostas na mesa. Todos podem apostar de novo. Depois &eacute; virada a quinta carta e todos podem apostar antes de revelar as cartas.</p>\n<p>&nbsp; &nbsp; &nbsp;Ap&oacute;s a exibi&ccedil;&atilde;o das cartas de cada jogador: quem, com suas cartas combinadas com as da mesa, tiver a combina&ccedil;&atilde;o mais valiosa &eacute; o <span style=\"text-decoration: underline;\">vencedor</span>. Em caso de empate o valor das apostas &eacute; divido entre os ganhadores de igual forma!</p></html>"); // NOI18N
        lblEscopoAjuda.setToolTipText("");

        btnSiteAjuda.setText("Saber mais");
        btnSiteAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiteAjudaActionPerformed(evt);
            }
        });

        lblUrlAjuda.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblUrlAjuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUrlAjuda.setText("www.pt.wikipedia.org/wiki/P%C3%B4quer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(lblEscopoAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(btnSiteAjuda))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(lblAjuda)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(198, Short.MAX_VALUE)
                    .addComponent(lblUrlAjuda)
                    .addContainerGap(199, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblAjuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEscopoAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSiteAjuda)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(351, Short.MAX_VALUE)
                    .addComponent(lblUrlAjuda)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiteAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiteAjudaActionPerformed

        try{
            java.awt.Desktop.getDesktop().browse(java.net.URI.create("https://pt.wikipedia.org/wiki/P%C3%B4quer"));
        }catch (Exception erro){
            JOptionPane.showMessageDialog(null, "Não foi possível abrir o site. Houve algum problema!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiteAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiteAjuda;
    private javax.swing.JLabel lblAjuda;
    private javax.swing.JLabel lblEscopoAjuda;
    private javax.swing.JLabel lblUrlAjuda;
    // End of variables declaration//GEN-END:variables
}
